version: '3.9'

services:
  php-fpm:
    build:
      context: ./docker/php-fpm
    container_name: 'php-fpm'
    ports:
      - '9000:9000'
    depends_on:
      - mysql
    volumes:
      - ./:/var/www/app

  nginx:
    image: nginx
    container_name: 'nginx'
    ports:
      - '80:80'
    depends_on:
      - php-fpm
    volumes:
      - ./:/var/www/app
      - ./docker/nginx/config/default.conf:/etc/nginx/conf.d/default.conf

  mysql:
    image: mysql:8.0
    volumes:
      - mysql:/var/lib/mysql
    container_name: 'database'
    command: "--default-authentication-plugin=mysql_native_password"
    restart: always
    environment:
      - "MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}"
      - "MYSQL_DATABASE=${MYSQL_DATABASE}"
      - "MYSQL_USER=${MYSQL_USER}"
      - "MYSQL_PASSWORD=${MYSQL_PASSWORD}"
    ports:
      - "3306:3306"

volumes:
  mysql:
